### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by zEpiixz** [TeamMoegMC/ImmersiveIndustry#2]
https://pastebin.com/PPUGjYDC

**Comment by HoovySimulator2** [comment]
Yey! I got the same crash! https://pastebin.com/E5V9Fr1v

**Comment by slasherbane** [comment]
Me too :(

**Comment by liuseniubi** [comment]
Some here

**Comment by JadianRadiator** [comment]
sam
[crash-2021-11-03_23.11.41-fml.txt](https://github.com/TeamMoegMC/ImmersiveIndustry/files/7472288/crash-2021-11-03_23.11.41-fml.txt)
e

**Comment by khjxiaogu** [comment]
I'm Sorry, this mod is not compatible with Immersive Engineering 5.0.4 or later version. Since IE changed a lot in api, and causing damage to existing saves.

**Comment by malte0811** [comment]
As an IE dev: We did not break any API in 5.0.4, we changed *internal* code that is not supposed to be used by addons. The only code that is considered API is in `blusunrize.immersiveengineering.api` and `blusunrize.lib.manual`, while the crash is due to a change in `blusunrize.immersiveengineering.common`.  
And "causing damage to existing saves" is news to me, if it's true no one has reported it yet.

**Comment by khjxiaogu** [comment]
> As an IE dev: We did not break any API in 5.0.4, we changed _internal_ code that is not supposed to be used by addons. The only code that is considered API is in `blusunrize.immersiveengineering.api` and `blusunrize.lib.manual`, while the crash is due to a change in `blusunrize.immersiveengineering.common`. And "causing damage to existing saves" is news to me, if it's true no one has reported it yet.

Sorry for my inaccurate expression, but updating to new IE version breaks multiblock BlockEntity data, and I got the exception: 
```
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at blusunrize.immersiveengineering.common.blocks.IEBaseTileEntity.getWorldNonnull(IEBaseTileEntity.java:228) ~[immersiveengineering:?]
	at blusunrize.immersiveengineering.common.blocks.generic.MultiblockPartTileEntity.getTileForPos(MultiblockPartTileEntity.java:433) ~[immersiveengineering:?]
	at blusunrize.immersiveengineering.common.blocks.generic.MultiblockPartTileEntity.master(MultiblockPartTileEntity.java:304) ~[immersiveengineering:?]
```
As This method is provided by IE, I refer to IE api. 
This exception breaks any existing IE multiblock structure.

**Comment by malte0811** [comment]
1. No one has reported this yet, so I'm pretty sure it's something on your end (`frostedheart:heat_radiator`). And a bunch of people *have* updated existing worlds to 5.0.4, so "breaks any existing IE multiblock structure" is simply wrong.
2. That is anything but a full stacktrace, the part you're showing only tells me that *something* is trying to get the master BE from a BE before it is properly added to the world.
3. IE API should only refer to the actual *API*, not to any IE code. And those methods are most certainly not part of the API.
4. While I'm at it, how about you *don't* blindly copy code from IE: https://github.com/TeamMoegMC/ImmersiveIndustry/blob/e03c0df008d6ab28c397dc87e487dc39110f942e/src/main/java/com/teammoeg/immersiveindustry/data/IIRecipeReloadListener.java#L58-L79 Neither of these methods should be called from addons.

**Comment by khjxiaogu** [comment]
> 1. No one has reported this yet, so I'm pretty sure it's something on your end (`frostedheart:heat_radiator`). And a bunch of people _have_ updated existing worlds to 5.0.4, so "breaks any existing IE multiblock structure" is simply wrong.
> 2. That is anything but a full stacktrace, the part you're showing only tells me that _something_ is trying to get the master BE from a BE before it is properly added to the world.
> 3. IE API should only refer to the actual _API_, not to any IE code. And those methods are most certainly not part of the API.
> 4. While I'm at it, how about you _don't_ blindly copy code from IE: https://github.com/TeamMoegMC/ImmersiveIndustry/blob/e03c0df008d6ab28c397dc87e487dc39110f942e/src/main/java/com/teammoeg/immersiveindustry/data/IIRecipeReloadListener.java#L58-L79
>     Neither of these methods should be called from addons.

Great Thanks for your advice. We would fix these problems later.
