### ISSUE TITLE
[1.16.5] Custom Electrolyzer recepies?

### ISSUE THREAD

**Issue by drago87** [TeamMoegMC/ImmersiveIndustry#6]
Is there a way to add Costom Electrolyzer recepies with either crafttweaker, cubejs or a data pack?

**Comment by khjxiaogu** [comment]
Sure, if you have ever read any of the codes:
[Example](https://github.com/TeamMoegMC/ImmersiveIndustry/blob/master/src/main/resources/data/immersiveindustry/recipes/electrolyze/alumium.json)
[Source](https://github.com/TeamMoegMC/ImmersiveIndustry/blob/master/src/main/java/com/teammoeg/immersiveindustry/content/electrolyzer/ElectrolyzerRecipeSerializer.java)

**Comment by drago87** [comment]
I'm having a problem that only fluids from minecraft and immersive engineering works as input.
Have tried fluids from these mods that dont work
kubejs
mekanism
create
immersive petrolium
woot
create craft & additions
pneumaticraft repressurized

I noticed that if you have 0 on the fluid output you dont get a recipe for the Industrial Electrolyzer. Would that be something you could add to a later version?

**Comment by khjxiaogu** [comment]
> I'm having a problem that only fluids from minecraft and immersive engineering works as input. 

Fluid input is an fluid tag input, you should use (or create) tags for input fluid to work. 

> I noticed that if you have 0 on the fluid output you dont get a recipe for the Industrial Electrolyzer. Would that be something you could add to a later version?

I can't really get you. Can you be more specific?

**Comment by drago87** [comment]
Totaly missed that it was a fluid tag

The probelm i have is if i set it to 0 or remove the fluid output alltogheter it only show the Simple Electrolyzer and the Industrial Electrolyzer tab in JEI is missing.


--EDIT-- now it works. dont know if there was something i did wrong or not
